### ISSUE TITLE
如果页面文件夹不是直接在pages/下，而是pages/里面又有一个文件夹放页面文件夹，则无法识别

### ISSUE THREAD

**Issue by Kaby-Lake** [LuckyHH/generated-plugin-taro-router-service#1]
如果代码结构如下：
![image](https://user-images.githubusercontent.com/49022571/151392832-407b6d68-a462-47ac-a839-2ddc30e77045.png)

单个页面的文件夹不是直接在pages/下面，而是pages/里面又有一个文件夹，这里面放单个页面文件夹，则无法识别（routerList里没有）

**Comment by xdoer** [comment]
我在 README 中有提到，只会把 pages 下的一级目录识别成页面。
![image](https://user-images.githubusercontent.com/22864183/151486838-1ef613e8-b407-4bb1-a8e0-ca9e2991e971.png)

小程序里页面结构很灵活，无论你把页面写到多么深的层级结构里，最后只要在 app.config.ts 里配置一下页面路径，就能使用 navigateTo 这类方法跳转过去。

但为了后面维护代码方便，还是建议页面都在 pages 下的一级目录里。这个工具基于这个约束条件，才可以自动配置 app.config.ts、project.config.json 等相关文件。

**Comment by xdoer** [comment]
还有一点就是没办法判断遍历到的这个文件到底是页面，还是组件

**Comment by Kaby-Lake** [comment]
好的，了解了，感谢回复。祝你新春快乐！
